[package]
name = "twiddle"
version = "0.1.0"
authors = ["Nicolette Verlinden <nicole@nicole.moe>"]

description = "Bit-twiddling utility functions"

documentation = "http://nicole.moe/docs/twiddle/index.html"
repository = "https://github.com/niconii/twiddle"

readme = "README.md"
keyword = ["bitwise", "bit", "bits"]

license = "MIT"
